server:
  port: 8989
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  redis:
    host: 106.13.236.137
    port: 7000
    database: 0
  data:
    elasticsearch:
      cluster-nodes: 192.168.43.128:9300
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.13.236.137:3306/search-rec-sys?characterEncoding=UTF-8
    username: root
    password: 111
mybatis:
  mapper-locations: classpath:com/csw/mapper/*.xml
  type-aliases-package: com.csw.entity # 别名 同样为 类名或者是类名首字母小写 User ===> User|user
# 日志
logging:
  level:
    com.csw.dao: debug
